#!/usr/bin/env bash

PID_FILE="/var/run/my_process.pid"
PROCESS="/alu-shell/processes_and_signals/manage_my_process"

case "$1" in
    start)
        nohup $PROCESS & echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE) && rm -f $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "No process found"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: 11-manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
